### PR TITLE
 a few edits to tic-tac-toe deliverable (WIP)

### PR DESCRIPTION
**Pull request by aimeemisaki**

### CODE REVIEW

**Comment by TaylorDarneille** [comment]
see slack message

**Comment by TaylorDarneille** [comment]
Hey Aimee - Paulina said she believed you ended up with a working TTT last night? The deployed version right now still has some bugs. Wanted to make sure this is your latest version? If so, are you available to try to hammer out those last bugs tonight?

**Comment by aimeemisaki** [comment]
Hi Taylor - Yes, I finished it last night. I believe I submitted my final
version last night... Perhaps, I didn't push it correctly. I will talk to
Paulina and submit it immediately after class is over. Thank you for your
patience!

Best,
Aimee

**Comment by TaylorDarneille** [comment]
You can still click on a cell twice to have it change from x to o, and if you win on the 9th cell, it registers as a tie.

**Pull request closed without merging**
